install.packages(c("xaringan", "metathis"))
install.packages("xaringanthemer", dependencies = TRUE)
install.packages("remotes")
remotes::install_github("gadenbuie/xaringanExtra")
install.packages("fontawesome")
